- name: Dotfiles | install bin
  copy:
    src: ../files/bin/
    dest: "{{ home }}/bin"
    owner: "{{ user }}"
    group: "{{ group }}"
    force: yes

- name: Dotfiles | install dircolors
  copy:
    src: ../files/dircolors
    dest: "{{ home }}/.dircolors"
    owner: "{{ user }}"
    group: "{{ group }}"
    force: yes

- name: Dotfiles | install tmux conf
  copy:
    src: ../files/tmux.conf
    dest: "{{ home }}/.tmux.conf"
    owner: "{{ user }}"
    group: "{{ group }}"
    force: yes

- name: Dotfiles | install vimrc
  copy:
    src: ../files/vimrc
    dest: "{{ home }}/.vimrc"
    owner: "{{ user }}"
    group: "{{ group }}"
    force: yes

- name: Dotfiles | install vim directory
  copy:
    src: ../files/vim/
    dest: "{{ home }}/.vim"
    owner: "{{ user }}"
    group: "{{ group }}"
    force: yes

- name: Dotfiles | create neovim config directory
  file:
    path: "/{{ home }}/{{ user }}/.config/nvim"
    state: directory

- name: Dotfiles | install neovim config
  copy:
    src: ../files/config/nvim/init.vim
    dest: "{{ home }}/.config/nvim/init.vim"
    owner: "{{ user }}"
    group: "{{ group }}"
    force: yes

- name: Dotfiles | install vim.local
  copy:
    src: ../files/vim.local
    dest: "{{ home }}/.vim.local"
    owner: "{{ user }}"
    group: "{{ group }}"
    force: yes

- name: Dotfiles | install vim plugins
  shell: vim -c "PlugInstall" -c "qa"
  become: yes
  become_user: "{{ user }}"

- name: Dotfiles | install zshrc
  copy:
    src: ../files/zshrc
    dest: "{{ home }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ group }}"
    force: yes

- name: Dotfiles | install zsh directory
  copy:
    src: ../files/zsh/
    dest: "{{ home }}/.zsh"
    owner: "{{ user }}"
    group: "{{ group }}"
    force: yes

- name: Dotfiles | install zshrc.local
  copy:
    src: ../files/zshrc.local
    dest: "{{ home }}/.zshrc.local"
    owner: "{{ user }}"
    group: "{{ group }}"
    force: yes
