. ~/.zsh/functions.zsh
. ~/.zsh/git.zsh
. ~/.zsh/agnoster.zsh-theme
load_file "aliases.zsh"
load_file "bindkeys.zsh"
load_file "completion.zsh"
load_file "environment.zsh"
load_file "exports.zsh"
load_file "setopt.zsh"

[ -e ~/.zshrc.local ] && . ~/.zshrc.local || true

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
